version: '3.4'

services:
  weatherforecast.api:
    image: ${DOCKER_REGISTRY-}weatherforecastapi
    build:
      context: .
      dockerfile: Services/WeatherForecast.API/Dockerfile
    
  whetherforecast.api:
    image: ${DOCKER_REGISTRY-}whetherforecastapi
    build:
      context: .
      dockerfile: Services/WhetherForecast.API/Dockerfile
    ports:
      - "7002:443"
